// what is String?
// sequince of carectors 
// agar single chahye tu ya use hoga

void main (){
var str= "shazia";
print(str);
}
// WHat is cancatinate ?
// cancatinate + jorna 
// agr concatinate r k data chahye (dono o jor kar )

void main (){
var Mname= "shazia";
var Fname= "Ahmed";
print(Mname + Fname);
// agar space  sath chahye ho tu 
print(Mname + ' ' + Fname);
}

// String Function
// lowerCase
// uparCase
// length
// trim

// lower case main chahye hotu 

void main (){
var str= "Shazia";
str=str.toLowerCase());
print(str);
}


// upparcase main chahyr ho 

void main (){
var str= "Shazia";
str=str.toUpparCase());
print(str);
}

// agr length main chahye ho tu 

void main (){
var str= "Shazia";
// "Shazia"; k length ko count karyga 
var l=str.length;
print(l);
}


// trim Space remove kar k length count karta hai

void main (){
var str= " Sha zia ";
str=str.trim();
var l=str.length;
print(l);
}

